### ISSUE TITLE
Remove my content from your theme!

### ISSUE THREAD

**Issue by ahmadawais** [varunalex/shades-of-blue-vscode#1]
You literally copy-pasted my 🦄 Shades of Purple theme's name for yours. I don't have any issue with the name but you are using the content from my theme which I didn't license to be copied.

I would appreciate if you can change the description and content of your theme to your own words and give me credit at the bottom of your `readme.md` file. 

CHANGE THE FOLLOWING:

`🦄 Shades of Blue — A professional theme with hand-picked & bold & italic shades of blue to go along with your VSCode.`

This is an exact copy/paste of my theme's description. Change this from your GitHub repo description, package.json, readme.md and where ever you used it.

Peace! ✌️

**Comment by varunalex** [comment]
Hi,

My intention was to provide similar theme with bluish color. Sorry about that.

Mentioned files are changed.

**Comment by ahmadawais** [comment]
@varunalex thanks for sharing that. I understand your point.

Can you remove the word `professional` as well? And release this update so all the descriptions are [updated on the marketplace too](https://marketplace.visualstudio.com/items?itemName=shades-of-blue.shades-of-blue)?

Here's a new theme description if you'd like to use it

> VSCode theme for developers who like the carefully crafted native blue colors.

Peace! ✌️
